LOGICAL_CHANNEL = "LOGICAL_CHANNEL"
TRANSCEIVER     = "TRANSCEIVER"
OTN             = "OTN"
ETHERNET        = "ETHERNET"
LLDP            = "LLDP"
PORT            = "PORT"
CLIENT_LANE_NUM = 4

MODULE_LIST = [
    {'Module': LOGICAL_CHANNEL,     'Field': 'transceiver',                         'show_name': 'Name'},
    {'Module': TRANSCEIVER,         'Field': 'present',                             'show_name': 'Exist'},
    {'Module': TRANSCEIVER,         'Field': 'vendor',                              'show_name': 'Vendor'},
    {'Module': TRANSCEIVER,         'Field': 'ethernet-pmd',                        'show_name': 'EthernetPmd'},
    {'Module': TRANSCEIVER,         'Field': 'mfg-date',                            'show_name': 'Manudate'},
    {'Module': TRANSCEIVER,         'Field': 'oui',                                 'show_name': 'oui'},
    {'Module': TRANSCEIVER,         'Field': 'part-no',                             'show_name': 'pn'},
    {'Module': TRANSCEIVER,         'Field': 'rn',                                  'show_name': 'rn'},
    {'Module': TRANSCEIVER,         'Field': 'serial-no',                           'show_name': 'sn'},
    {'Module': TRANSCEIVER,         'Field': 'identifier',                          'show_name': 'Identifier'},
    {'Module': TRANSCEIVER,         'Field': 'cmis-revision',                       'show_name': 'cmisRevision'},
    {'Module': TRANSCEIVER,         'Field': 'form-factor',                         'show_name': 'ModuleType'},
    {'Module': TRANSCEIVER,         'Field': 'connector-type',                      'show_name': 'ContectType'},
    {'Module': TRANSCEIVER,         'Field': 'wavelength',                          'show_name': 'Wavelength(nm)'},
    {'Module': TRANSCEIVER,         'Field': 'wavelength-tolerance',                'show_name': 'Wavelength Tolerance(nm)'},
    {'Module': TRANSCEIVER,         'Field': 'vcc-low-alarm-threshold',             'show_name': 'Voltage Low Th(mV)'},
    {'Module': TRANSCEIVER,         'Field': 'vcc-high-alarm-threshold',            'show_name': 'Voltage High Th(mV)'},
    {'Module': TRANSCEIVER,         'Field': 'rx-total-power-low-alarm-threshold',  'show_name': 'Rxpwr Low Th(dBm)'},
    {'Module': TRANSCEIVER,         'Field': 'rx-total-power-high-alarm-threshold', 'show_name': 'Rxpwr High Th(dBm)'},
    {'Module': TRANSCEIVER,         'Field': 'tx-power-low-alarm-threshold',        'show_name': 'Txpwr Low Th(dBm)'},
    {'Module': TRANSCEIVER,         'Field': 'tx-power-high-alarm-threshold',       'show_name': 'Txpwr High Th(dBm)'},
    {'Module': TRANSCEIVER,         'Field': 'tx-bais-low-alarm-threshold',         'show_name': 'Txbias Low Th(mA)'},    
    {'Module': TRANSCEIVER,         'Field': 'tx-bais-high-alarm-threshold',        'show_name': 'Txbias High Th(mA)'},    
]

STATE_LIST = [
    {'Module': LOGICAL_CHANNEL,   'Field': 'transceiver',                     'show_name': 'Name'},
    {'Module': TRANSCEIVER,       'Field': 'present',                         'show_name': 'Exist'},
    {'Module': LOGICAL_CHANNEL,   'Field': 'admin-state',                     'show_name': 'PortAdmin'},
    {'Module': TRANSCEIVER,       'Field': 'enabled',                         'show_name': 'TxLaser'},
    {'Module': TRANSCEIVER,       'Field': 'power-mode',                      'show_name': 'PowerMode'},
    {'Module': TRANSCEIVER,       'Field': 'ethernet-pmd-preconf',            'show_name': 'PrecfgType'},
    {'Module': TRANSCEIVER,       'Field': 'fec-mode',                        'show_name': 'FecMode'},
    {'Module': LOGICAL_CHANNEL,   'Field': 'loopback-mode',                   'show_name': 'LoopBack'},
    {'Module': LOGICAL_CHANNEL,   'Field': 'test-signal',                     'show_name': 'prbs'},
    {'Module': LOGICAL_CHANNEL,   'Field': 'test-signal-pattern',             'show_name': 'prbsPattern'},
    {'Module': LOGICAL_CHANNEL,   'Field': 'link-down-delay-mode',            'show_name': 'LinkDownDelayMode'},
    {'Module': LOGICAL_CHANNEL,   'Field': 'link-down-delay-hold-off',        'show_name': 'LinkDownDelayHoldoff(ms)'},
    {'Module': LOGICAL_CHANNEL,   'Field': 'link-up-delay-mode',              'show_name': 'LinkUpDelayMode'},
    {'Module': LOGICAL_CHANNEL,   'Field': 'link-up-delay-hold-off',          'show_name': 'LinkUpDelayHoldoff(s)'},
    {'Module': LOGICAL_CHANNEL,   'Field': 'link-up-delay-active-threshold',  'show_name': 'LinkUpDelayActiveThreshold(ms)'},
    {'Module': OTN,               'Field': 'delay-measurement-enabled',       'show_name': 'DelayMeasAutoEnable'},
    {'Module': ETHERNET,          'Field': 'client-rx-als',                   'show_name': 'ClientAlsClientRxSwitch'},
    {'Module': ETHERNET,          'Field': 'client-rx-als-delay',             'show_name': 'ClientAlsClientRxHoldoff(ms)'},
    {'Module': ETHERNET,          'Field': 'client-als',                      'show_name': 'ClientAlsClientTxSwitch'},
    {'Module': ETHERNET,          'Field': 'als-delay',                       'show_name': 'ClientAlsClientTxHoldoff(ms)'},
    {'Module': ETHERNET,          'Field': 'client-als',                      'show_name': 'ClientAlsLineRxSwitch'},
    {'Module': ETHERNET,          'Field': 'als-delay',                       'show_name': 'ClientAlsLineRxHoldoff(ms)'},
    {'Module': ETHERNET,          'Field': 'maintenance',                     'show_name': 'ForceInsert'},
    {'Module': LLDP,              'Field': 'enabled',                         'show_name': 'LldpEnable'},
    
    {'Module': TRANSCEIVER,       'Field': 'extend-module-code',              'show_name': 'ExtendModuleCode'},
    {'Module': TRANSCEIVER,       'Field': 'data-status',                     'show_name': 'Datastatus'},
    {'Module': TRANSCEIVER,       'Field': 'encode',                          'show_name': 'Encode'},
    {'Module': TRANSCEIVER,       'Field': 'bitrate',                         'show_name': 'Bitrate(Gbit)'},
    {'Module': TRANSCEIVER,       'Field': 'extend-bit-rate',                 'show_name': 'Extendbitrate(Gbit)'},
    {'Module': LOGICAL_CHANNEL,   'Field': 'link-state',                      'show_name': 'GeLinkState'},
    {'Module': LOGICAL_CHANNEL,   'Field': 'trib-protocol',                   'show_name': 'ClientMode'},
    {'Module': PORT,              'Field': 'led-color',                       'show_name': 'LedState'},   
]
 
CONFIG_LIST = [
    {'Module': LOGICAL_CHANNEL,   'Field': 'transceiver',                     'show_name': 'Name'},
    {'Module': LOGICAL_CHANNEL,   'Field': 'admin-state',                     'show_name': 'PortAdmin'},
    {'Module': TRANSCEIVER,       'Field': 'enabled',                         'show_name': 'TxLaser'},
    {'Module': TRANSCEIVER,       'Field': 'power-mode',                      'show_name': 'PowerMode'},
    {'Module': TRANSCEIVER,       'Field': 'ethernet-pmd-preconf',            'show_name': 'PrecfgType'},
    {'Module': TRANSCEIVER,       'Field': 'fec-mode',                        'show_name': 'FecMode'},
    {'Module': LOGICAL_CHANNEL,   'Field': 'loopback-mode',                   'show_name': 'LoopBack'},
    {'Module': LOGICAL_CHANNEL,   'Field': 'test-signal',                     'show_name': 'prbs'},
    {'Module': LOGICAL_CHANNEL,   'Field': 'test-signal-pattern',             'show_name': 'prbsPattern'},
    {'Module': LOGICAL_CHANNEL,   'Field': 'link-down-delay-mode',            'show_name': 'LinkDownDelayMode'},
    {'Module': LOGICAL_CHANNEL,   'Field': 'link-down-delay-hold-off',        'show_name': 'LinkDownDelayHoldoff(ms)'},
    {'Module': LOGICAL_CHANNEL,   'Field': 'link-up-delay-mode',              'show_name': 'LinkUpDelayMode'},
    {'Module': LOGICAL_CHANNEL,   'Field': 'link-up-delay-hold-off',          'show_name': 'LinkUpDelayHoldoff(s)'},
    {'Module': LOGICAL_CHANNEL,   'Field': 'link-up-delay-active-threshold',  'show_name': 'LinkUpDelayActiveThreshold(ms)'},
    {'Module': OTN,               'Field': 'delay-measurement-enabled',       'show_name': 'DelayMeasAutoEnable'},
    {'Module': ETHERNET,          'Field': 'client-rx-als',                   'show_name': 'ClientAlsClientRxSwitch'},
    {'Module': ETHERNET,          'Field': 'client-rx-als-delay',             'show_name': 'ClientAlsClientRxHoldoff(ms)'},
    {'Module': ETHERNET,          'Field': 'client-als',                      'show_name': 'ClientAlsClientTxSwitch'},
    {'Module': ETHERNET,          'Field': 'als-delay',                       'show_name': 'ClientAlsClientTxHoldoff(ms)'},
    {'Module': ETHERNET,          'Field': 'client-als',                      'show_name': 'ClientAlsLineRxSwitch'},
    {'Module': ETHERNET,          'Field': 'als-delay',                       'show_name': 'ClientAlsLineRxHoldoff(ms)'},
    {'Module': ETHERNET,          'Field': 'maintenance',                     'show_name': 'ForceInsert'},
    {'Module': LLDP,              'Field': 'enabled',                         'show_name': 'LldpEnable'},
]

LLDP_LIST = [
    {'Module': LOGICAL_CHANNEL,     'Field': 'transceiver',                           'show_name': 'Port Name'},
    {'Module': LLDP,                'Field': 'neighbor-system-name',                  'show_name': 'systemName'},
    {'Module': LLDP,                'Field': 'neighbor-system-description',           'show_name': 'systemDecription'},
    {'Module': LLDP,                'Field': 'neighbor-chassis-id',                   'show_name': 'chassisId'},
    {'Module': LLDP,                'Field': 'neighbor-port-id',                      'show_name': 'portId'},
    {'Module': LLDP,                'Field': 'neighbor-port-description',             'show_name': 'portDescription'},
    {'Module': LLDP,                'Field': 'neighbor-management-address',           'show_name': 'managementAddress'},
    {'Module': LLDP,                'Field': 'neighbor-management-address-type',      'show_name': 'managementAddressType'},
    {'Module': LLDP,                'Field': 'neighbor-chassis-id-type',              'show_name': 'chassisIdType'},
    {'Module': LLDP,                'Field': 'neighbor-port-id-type',                 'show_name': 'portIdType'},
    {'Module': LLDP,                'Field': 'neighbor-last-update',                  'show_name': 'lastUpdated'},
]

RMON_LIST = [
    {'Module': LOGICAL_CHANNEL,     'Field': 'transceiver',                         'show_name': 'Name'},
    {'Module': ETHERNET,            'Field': 'tx-good-frame', 		                'show_name': 'rmon-good-frame-tx'},
    {'Module': ETHERNET,            'Field': 'tx-good-octets', 		                'show_name': 'rmon-good-octets-tx'},
    {'Module': ETHERNET,            'Field': 'tx-good-multicast', 		            'show_name': 'rmon-good-multicast-tx'},
    {'Module': ETHERNET,            'Field': 'tx-good-broadcast', 		            'show_name': 'rmon-good-broadcast-tx'},
    {'Module': ETHERNET,            'Field': 'tx-good-64b', 		                'show_name': 'rmon-good-64b-tx'},
    {'Module': ETHERNET,            'Field': 'tx-good-65b-127b', 		            'show_name': 'rmon-good-65b-127b-tx'},
    {'Module': ETHERNET,            'Field': 'tx-good-128b-255b',		            'show_name': 'rmon-good-128b-255b-tx'},
    {'Module': ETHERNET,            'Field': 'tx-good-256b-511b',		            'show_name': 'rmon-good-256b-511b-tx'},
    {'Module': ETHERNET,            'Field': 'tx-good-512b-1023b',		            'show_name': 'rmon-good-512b-1023b-tx'},
    {'Module': ETHERNET,            'Field': 'tx-good-1024b-1518b',		            'show_name': 'rmon-good-1024b-1518b-tx'},
    {'Module': ETHERNET,            'Field': 'tx-good-1519b-ltj',		            'show_name': 'rmon-good-1519b-LTJ-tx'},
    {'Module': ETHERNET,            'Field': 'tx-good-jumbo', 		                'show_name': 'rmon-good-jumbo-tx'},
    {'Module': ETHERNET,            'Field': 'tx-bad-frame', 		                'show_name': 'rmon-bad-frame-tx'},
    {'Module': ETHERNET,            'Field': 'tx-bad-octets', 		                'show_name': 'rmon-bad-octets-tx'},
    {'Module': ETHERNET,            'Field': 'tx-bad-multicast',		            'show_name': 'rmon-bad-multicast-tx'},
    {'Module': ETHERNET,            'Field': 'tx-bad-broadcast',		            'show_name': 'rmon-bad-broadcast-tx'},
    {'Module': ETHERNET,            'Field': 'out-crc-errors', 		                'show_name': 'out-crc-errors'},
    {'Module': ETHERNET,            'Field': 'tx-bad-lt-64b', 		                'show_name': 'rmon-bad-lt-64b-tx'},
    {'Module': ETHERNET,            'Field': 'tx-bad-64b', 		                    'show_name': 'rmon-bad-64b-tx'},
    {'Module': ETHERNET,            'Field': 'tx-bad-65b-127b', 		            'show_name': 'rmon-bad-65b-127b-tx'},
    {'Module': ETHERNET,            'Field': 'tx-bad-128b-255b',		            'show_name': 'rmon-bad-128b-255b-tx'},
    {'Module': ETHERNET,            'Field': 'tx-bad-256b-511b',		            'show_name': 'rmon-bad-256b-511b-tx'},
    {'Module': ETHERNET,            'Field': 'tx-bad-512b-1023b',		            'show_name': 'rmon-bad-512b-1023b-tx'},
    {'Module': ETHERNET,            'Field': 'tx-bad-1024b-1518b',		            'show_name': 'rmon-bad-1024b-1518b-tx'},
    {'Module': ETHERNET,            'Field': 'tx-bad-1519b-ltj',		            'show_name': 'rmon-bad-1519b-LTJ-tx'},
    {'Module': ETHERNET,            'Field': 'tx-bad-jumbo', 		                'show_name': 'rmon-bad-jumbo-tx'},
    {'Module': ETHERNET,            'Field': 'tx-octets', 		                    'show_name': 'rmon-octets-tx'},
    {'Module': ETHERNET,            'Field': 'tx-frame', 		                    'show_name': 'rmon-frame-tx'},
    {'Module': ETHERNET,            'Field': 'tx-broadcast', 		                'show_name': 'rmon-broadcast-tx'},
    {'Module': ETHERNET,            'Field': 'tx-multicast', 		                'show_name': 'rmon-multicast-tx'},
    {'Module': ETHERNET,            'Field': 'tx-crc-align', 		                'show_name': 'rmon-crc-align-tx'},
    {'Module': ETHERNET,            'Field': 'tx-under-size', 		                'show_name': 'rmon-under-size-tx'},
    {'Module': ETHERNET,            'Field': 'tx-over-size', 		                'show_name': 'rmon-over-size-tx'},
    {'Module': ETHERNET,            'Field': 'tx-fragment', 		                'show_name': 'rmon-fragment-tx'},
    {'Module': ETHERNET,            'Field': 'tx-jabber', 		                    'show_name': 'rmon-jabbers-tx'},
    {'Module': ETHERNET,            'Field': 'tx-64b', 		                        'show_name': 'rmon-64b-tx'},
    {'Module': ETHERNET,            'Field': 'tx-65b-127b', 		                'show_name': 'rmon-65b-127b-tx'},
    {'Module': ETHERNET,            'Field': 'tx-128b-255b', 		                'show_name': 'rmon-128b-255b-tx'},
    {'Module': ETHERNET,            'Field': 'tx-256b-511b', 		                'show_name': 'rmon-256b-511b-tx'},
    {'Module': ETHERNET,            'Field': 'tx-512b-1023b', 		                'show_name': 'rmon-512b-1023b-tx'},
    {'Module': ETHERNET,            'Field': 'tx-1024b-1518b', 		                'show_name': 'rmon-1024b-1518b-tx'},
    {'Module': ETHERNET,            'Field': 'tx-1519b-max', 		                'show_name': 'rmon-1519b-max-tx'},
    {'Module': ETHERNET,            'Field': 'rx-good-frame', 		                'show_name': 'rmon-good-frame-rx'},
    {'Module': ETHERNET,            'Field': 'rx-good-octets', 		                'show_name': 'rmon-good-octets-rx'},
    {'Module': ETHERNET,            'Field': 'rx-good-multicast',		            'show_name': 'rmon-good-multicast-rx'},
    {'Module': ETHERNET,            'Field': 'rx-good-broadcast',		            'show_name': 'rmon-good-broadcast-rx'},
    {'Module': ETHERNET,            'Field': 'rx-good-64b', 		                'show_name': 'rmon-good-64b-rx'},
    {'Module': ETHERNET,            'Field': 'rx-good-65b-127b',		            'show_name': 'rmon-good-65b-127b-rx'},
    {'Module': ETHERNET,            'Field': 'rx-good-128b-255b',		            'show_name': 'rmon-good-128b-255b-rx'},
    {'Module': ETHERNET,            'Field': 'rx-good-256b-511b',		            'show_name': 'rmon-good-256b-511b-rx'},
    {'Module': ETHERNET,            'Field': 'rx-good-512b-1023b',		            'show_name': 'rmon-good-512b-1023b-rx'},
    {'Module': ETHERNET,            'Field': 'rx-good-1024b-1518b',		            'show_name': 'rmon-good-1024b-1518b-rx'},
    {'Module': ETHERNET,            'Field': 'rx-good-1519b-ltj',		            'show_name': 'rmon-good-1519b-LTJ-rx'},
    {'Module': ETHERNET,            'Field': 'rx-good-jumbo', 		                'show_name': 'rmon-good-jumbo-rx'},
    {'Module': ETHERNET,            'Field': 'rx-bad-frame', 		                'show_name': 'rmon-bad-frame-rx'},
    {'Module': ETHERNET,            'Field': 'rx-bad-octets', 		                'show_name': 'rmon-bad-octets-rx'},
    {'Module': ETHERNET,            'Field': 'rx-bad-multicast',		            'show_name': 'rmon-bad-multicast-rx'},
    {'Module': ETHERNET,            'Field': 'rx-bad-broadcast',		            'show_name': 'rmon-bad-broadcast-rx'},
    {'Module': ETHERNET,            'Field': 'in-crc-errors', 		                'show_name': 'in-crc-errors'},
    {'Module': ETHERNET,            'Field': 'rx-bad-lt-64b', 		                'show_name': 'rmon-bad-lt-64b-rx'},
    {'Module': ETHERNET,            'Field': 'rx-bad-64b', 		                    'show_name': 'rmon-bad-64b-rx'},
    {'Module': ETHERNET,            'Field': 'rx-bad-65b-127b', 		            'show_name': 'rmon-bad-65b-127b-rx'},
    {'Module': ETHERNET,            'Field': 'rx-bad-128b-255b',		            'show_name': 'rmon-bad-128b-255b-rx'},
    {'Module': ETHERNET,            'Field': 'rx-bad-256b-511b',		            'show_name': 'rmon-bad-256b-511b-rx'},
    {'Module': ETHERNET,            'Field': 'rx-bad-512b-1023b',		            'show_name': 'rmon-bad-512b-1023b-rx'},
    {'Module': ETHERNET,            'Field': 'rx-bad-1024b-1518b',		            'show_name': 'rmon-bad-1024b-1518b-rx'},
    {'Module': ETHERNET,            'Field': 'rx-bad-1519b-ltj',		            'show_name': 'rmon-bad-1519b-LTJ-rx'},
    {'Module': ETHERNET,            'Field': 'rx-bad-jumbo', 		                'show_name': 'rmon-bad-jumbo-rx'},
    {'Module': ETHERNET,            'Field': 'rx-octets', 		                    'show_name': 'rmon-octets-rx'},
    {'Module': ETHERNET,            'Field': 'rx-frame', 		                    'show_name': 'rmon-frame-rx'},
    {'Module': ETHERNET,            'Field': 'rx-broadcast', 		                'show_name': 'rmon-broadcast-rx'},
    {'Module': ETHERNET,            'Field': 'rx-multicast', 		                'show_name': 'rmon-multicast-rx'},
    {'Module': ETHERNET,            'Field': 'rx-crc-align', 		                'show_name': 'rmon-crc-align-rx'},
    {'Module': ETHERNET,            'Field': 'in-undersize-frames', 		        'show_name': 'in-undersize-frames'},
    {'Module': ETHERNET,            'Field': 'in-oversize-frames', 		            'show_name': 'in-oversize-frames'},
    {'Module': ETHERNET,            'Field': 'in-fragment-frames', 		            'show_name': 'in-fragment-frames'},
    {'Module': ETHERNET,            'Field': 'in-jabber-frames', 		            'show_name': 'in-jabber-frames'},
    {'Module': ETHERNET,            'Field': 'rx-64b', 		                        'show_name': 'rmon-64b-rx'},
    {'Module': ETHERNET,            'Field': 'rx-65b-127b', 		                'show_name': 'rmon-65b-127b-rx'},
    {'Module': ETHERNET,            'Field': 'rx-128b-255b', 		                'show_name': 'rmon-128b-255b-rx'},
    {'Module': ETHERNET,            'Field': 'rx-256b-511b', 		                'show_name': 'rmon-256b-511b-rx'},
    {'Module': ETHERNET,            'Field': 'rx-512b-1023b', 		                'show_name': 'rmon-512b-1023b-rx'},
    {'Module': ETHERNET,            'Field': 'rx-1024b-1518b', 		                'show_name': 'rmon-1024b-1518b-rx'},
    {'Module': ETHERNET,            'Field': 'rx-1519b-max', 		                'show_name': 'rmon-1519b-max-rx'},
    {'Module': ETHERNET,            'Field': 'last-clean-up', 		                'show_name': 'last-clean-up'},
]

PM_LIST = [
    {'Module': TRANSCEIVER,         'Field': 'InputPower',                          'show_name': 'RxPowerTotal(dBm)'},
    {'Module': TRANSCEIVER,         'Field': 'OutputPower',                         'show_name': 'TxPowerTotal(dBm)'},
    {'Module': TRANSCEIVER,         'Field': 'Temperature',                         'show_name': 'Temp(C)'},
    {'Module': TRANSCEIVER,         'Field': 'LaserBiasVoltage',                    'show_name': 'Voltage(mV)'},
    {'Module': TRANSCEIVER,         'Field': 'PreFecBer',                           'show_name': 'PreFecBer'},
    {'Module': OTN,                 'Field': 'Delay',                               'show_name': 'DelayMeasureValue(us)'},
]

LANE_PM_LIST = [
    {'Module': TRANSCEIVER,         'Field': "InputPower",                          'show_name': "InputPower(dBm)"},
    {'Module': TRANSCEIVER,         'Field': "OutputPower",                         'show_name': "OutputPower(dBm)"},
    {'Module': TRANSCEIVER,         'Field': "LaserBiasCurrent",                    'show_name': "LaserBias(mA)"},
]

GE_PM_LIST = [
    {'Module': TRANSCEIVER,     'Field': 'loss-time', 				            'show_name': 'LossTime(s)'},
    {'Module': TRANSCEIVER,     'Field': 'fec-uncorrectable-words', 			'show_name': 'FEC Uncorrectable Words'},
    {'Module': ETHERNET,        'Field': 'in-undersize-frames', 			    'show_name': 'InUndersizePkts'},
    {'Module': ETHERNET,        'Field': 'in-oversize-frames', 				    'show_name': 'InOversizePkts'},
    {'Module': ETHERNET,        'Field': 'in-jabber-frames', 				    'show_name': 'InJabbers'},
    {'Module': ETHERNET,        'Field': 'in-fragment-frames', 				    'show_name': 'InFragments'},
    {'Module': ETHERNET,        'Field': 'in-pcs-bip-errors', 				    'show_name': 'In PCS CV'},
    {'Module': ETHERNET,        'Field': 'in-pcs-errored-seconds', 				'show_name': 'In PCS ES'},
    {'Module': ETHERNET,        'Field': 'in-pcs-severely-errored-seconds', 	'show_name': 'In PCS SES'},
    {'Module': ETHERNET,        'Field': 'in-pcs-unavailable-seconds', 			'show_name': 'In PCS UAS'},
    {'Module': ETHERNET,        'Field': 'out-crc-errors', 				        'show_name': 'OutErrors'},
    {'Module': ETHERNET,        'Field': 'rx-64b', 				                'show_name': 'InPkts64Octets'},
    {'Module': ETHERNET,        'Field': 'rx-65b-127b', 				        'show_name': 'InPkts65to127Octets'},
    {'Module': ETHERNET,        'Field': 'rx-128b-255b', 				        'show_name': 'InPkts128to255Octets'},
    {'Module': ETHERNET,        'Field': 'rx-256b-511b', 				        'show_name': 'InPkts256to511Octets'},
    {'Module': ETHERNET,        'Field': 'rx-512b-1023b', 				        'show_name': 'InPkts512to1023Octets'},
    {'Module': ETHERNET,        'Field': 'rx-1024b-1518b', 				        'show_name': 'InPkts1024to1518Octets'},
    {'Module': ETHERNET,        'Field': 'rx-octets', 				            'show_name': 'InOctets'},
    {'Module': ETHERNET,        'Field': 'rx-multicast', 				        'show_name': 'InMulticastPkts'},
    {'Module': ETHERNET,        'Field': 'rx-broadcast', 				        'show_name': 'InBroadcastPkts'},
    {'Module': ETHERNET,        'Field': 'rx-frame', 				            'show_name': 'InPkts'},
    {'Module': ETHERNET,        'Field': 'rx-crc-align', 				        'show_name': 'InCRCAlignErrors'},
    {'Module': ETHERNET,        'Field': 'tx-octets', 				            'show_name': 'OutOctets'},
    {'Module': ETHERNET,        'Field': 'tx-multicast', 				        'show_name': 'OutMulticastPkts'},
    {'Module': ETHERNET,        'Field': 'tx-broadcast', 				        'show_name': 'OutBroadcastPkts'},
    {'Module': ETHERNET,        'Field': 'tx-frame', 				            'show_name': 'OutPkts'},
]